# Generated by Django 5.2.1 on 2025-05-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bank_options_alter_branch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': False},
        ),
    ]
